services:
  db:
    image: postgres:16-alpine
    container_name: precificacao-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: precificacao-backend
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      LDAP_URL: ${LDAP_URL}
      AD_DOMAIN: ${AD_DOMAIN}
    volumes:
      - /mnt/datalake_realengo:/mnt/datalake_realengo:ro
      - ./backend/config:/app/config
    command: "./entrypoint.sh"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: precificacao-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
